- name: app set up
  include_role:
    name: common
    tasks_from: app-setup

- name: app set up
  include_role:
    name: common
    tasks_from: maven

- name: app set up
  include_role:
    name: common
    tasks_from: python

- name: import data
  community.mysql.mysql_db:
    name: all
    login_user: "{{ MYSQL_USER }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"
    state: import
    target: "{{item}}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: system set up
  include_role:
    name: common
    tasks_from: systemd.yaml
