- name: Create service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon-reload: true
- name: start and enable catalogue
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes