- name: Create service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon-reload: true
- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes