- name: error handling
  hosts: local
  connection: local
  tasks:
  - name: check user
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: create user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0

  - name: user Existing
    ansible.builtin.debug:
      msg: "user already exist"
    when: output.rc == 0
