- name: MONGODB SET UP
  hosts: mongodb
  become: yes
  tasks:
  - name: Creating Mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongodb.repo
  - name: installing mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
  - name: Starting mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: Changing port
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: Restarting mongodb
    ansible.builtin.service :
      name: mongod
      state: restarted
    
  

