- name: USER SET UP
  hosts: user
  become: yes
  tasks:
  - name: Remove existing nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: Enaable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -yes
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: create user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip
  - name: Extract code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    community.general.npm:
      path: /app
  - name: create service 
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/user.service
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: starte and enable
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
 